sudo : false

notifications:
  email: false

language: C++

compiler: 
    - gcc

cache: 
  directories:
    - programs

install:
    - ./contrib/utilities/download_clang_format

script: 
    - ./contrib/utilities/check_indentation.sh 
    - mkdir build
    - cd build
    - cmake -DDEAL_II_COMPONENT_DOCUMENTATION=ON ..
    - make documentation  

branches:
  only:
    - master
