sudo : false

notifications:
  email: false

language: C++

compiler: 
    - gcc

cache: 
  directories:
    - programs

addons:
  apt:
    packages:
      - doxygen

before_install:
    - sudo apt-get -y install graphviz perl texlive-latex-recommended ghostscript

install:
    - ./contrib/utilities/download_clang_format

script: 
#    - ./contrib/utilities/check_indentation.sh 
    - mkdir build
    - cd build
    - cmake -DDEAL_II_COMPONENT_DOCUMENTATION=ON ..
    - travis_wait 60 make -j documentation
    - cat _formulas.log  
    - cat doxygen.log && ! [ -s doxygen.log ]

branches:
  only:
    - master
