# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: CMake@1
  inputs:
    workingDirectory: 'build' # Optional
    #cmakeArgs: # Optional
- script: |
    make
  displayName: 'make'
