name: github-linux

on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  linux-debug-cuda-11:
    # simple parallel debug build using cuda-11

    name: linux debug cuda-11
    runs-on: [ubuntu-20.04]

    env:
      CUDA_ROOT: /usr/local/cuda

    steps:
    - uses: actions/checkout@v3
    - name: modules
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
        sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ginggs/deal.ii-9.4.0-backports
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends \
            cuda-toolkit-11-3 \
            libp4est-dev \
            libopenmpi-dev \
            openmpi-bin
    - name: info
      run: |
        mpicc -v
        cmake --version
    - uses: actions/checkout@v2
      with:
        repository: kokkos/kokkos
        ref: 3.7.00
        path: kokkos
    - name: install kokkos
      working-directory: kokkos
      run: |
        mkdir build
        cd build
        cmake -D BUILD_SHARED_LIBS=ON \
              -D CMAKE_CXX_COMPILER=${GITHUB_WORKSPACE}/kokkos/bin/nvcc_wrapper \
              -D CMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/kokkos-install \
              -D Kokkos_ENABLE_CUDA=ON \
              -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
              -D Kokkos_ARCH_VOLTA70=ON \
              ..
        make install
    - name: configure
      run: |
        cmake -D CMAKE_BUILD_TYPE=Debug \
              -D CMAKE_CXX_COMPILER=${GITHUB_WORKSPACE}/kokkos/bin/nvcc_wrapper \
              -D DEAL_II_CUDA_FLAGS='-arch=sm_70' \
              -D DEAL_II_CXX_FLAGS='-Werror -Wno-non-template-friend' \
              -D DEAL_II_EARLY_DEPRECATIONS=ON \
              -D DEAL_II_WITH_CUDA="ON" \
              -D DEAL_II_WITH_KOKKOS="ON" \
              -D KOKKOS_DIR=${GITHUB_WORKSPACE}/kokkos-install \
              -D DEAL_II_WITH_MPI="ON" \
              -D DEAL_II_WITH_P4EST="ON" \
              -D DEAL_II_COMPONENT_EXAMPLES="ON" \
              .
    - name: archive
      uses: actions/upload-artifact@v3
      with:
        name: linux-cuda-detailed.log
        path: detailed.log
    - name: build
      run: |
        make -j 2
