name: linux

on:
  push:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 4
  MAKEFLAGS: "--jobs=4"

jobs:

 ####################
  # clang-23-modules #
  ####################

  clang-23-modules:
    # simple build testing C++20 modules

    name: debian bookworm clang-23 modules
    runs-on: [ubuntu-latest]
    container:
      image: dealii/dependencies:noble-v9.7.1

    # The following condition only runs the workflow on 'push' or if the
    # 'pull_request' is not a draft. This is only useful for hackathons or
    # other situations when the CI is massively overburdened with pull
    # requests.
    #
    # if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    steps:
    - name: modules
      run: |
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends \
            ninja-build wget lsb-release software-properties-common gnupg g++-14
        sudo wget https://apt.llvm.org/llvm.sh && sudo chmod +x llvm.sh && sudo ./llvm.sh 23
    - uses: actions/checkout@v6
      with:
        repository: kokkos/kokkos
        ref: 5.0.1
        path: kokkos
    - name: compile and install kokkos
      working-directory: kokkos
      run: |
        mkdir build
        cd build
        cmake -GNinja \
              -D BUILD_SHARED_LIBS=ON \
              -D CMAKE_CXX_COMPILER=clang++-23 \
              -D CMAKE_CXX_STANDARD=23 \
              -D CMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/../kokkos-install \
              ..
        ninja install
    - uses: actions/checkout@v6
    - name: configure deal.II
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_BUILD_TYPE=Debug \
              -D CMAKE_CXX_STANDARD=23 \
              -D CMAKE_C_COMPILER=clang-23 \
              -D CMAKE_CXX_COMPILER=clang++-23 \
              -D DEAL_II_EARLY_DEPRECATIONS=ON \
              -D DEAL_II_WITH_CXX20_MODULE=ON \
              -D DEAL_II_WITH_TASKFLOW=OFF \
              -D DEAL_II_WITH_CGAL=OFF \
              -D KOKKOS_DIR=${GITHUB_WORKSPACE}/../kokkos-install \
              -G Ninja \
              ..
    - name: print detailed.log
      run: cat build/detailed.log
    - name: build deal.II
      run: |
        cd build
        ninja --verbose dealii_module_debug
