name: Spell Check with Typos
on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.actor }}-${{ github.ref }}-typos
  cancel-in-progress: true

permissions: write-all

jobs:
  typos-check:
    name: Check for new typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling with typos
        uses: crate-ci/typos@v1.23.6
        with:
          write_changes: true
          config: ./.typos.toml
          files: doc examples include source
