name: windows

on:
  push:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_OUTPUT_ON_FAILURE: 1
  # test only in serial to avoid file locking error on ZERO_CHECK.lastbuildstate
  CTEST_PARALLEL_LEVEL: 1

jobs:
  serial:
    # Serial build on Windows

    name: ${{ matrix.os }} serial
    runs-on: ${{ matrix.os }}

    #
    # The following condition only runs the workflow on 'push' or if the
    # 'pull_request' is not a draft. This is only useful for hackathons or
    # other situations when the CI is massively overburdened with pull
    # requests.
    #
    # if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]

    steps:
    - uses: actions/checkout@v7
    - name: set up path
      # needed to use GNU patch instead of Strawberry Perl patch
      run: |
        echo "c:\program files\git\usr\bin" >> $env:GITHUB_PATH
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.4.2'
    - name: info
      run: |
        patch --version
        cmake --version
    - name: configure
      shell: pwsh
      run: |
        cmake -B build `
          -DCMAKE_C_FLAGS_DEBUG="/Zi /Ob0 /Od /MDd" `
          -DCMAKE_CXX_FLAGS_DEBUG="/Zi /Ob0 /Od /MDd" `
          -DCMAKE_MSVC_RUNTIME_CHECKS="" `
          -DCMAKE_INSTALL_PREFIX="C:/project" `
          -DDEAL_II_CXX_FLAGS="/WX /std:c++20 /D FE_EVAL_FACTORY_DEGREE_MAX=2" `
          -T host=x64 `
          -A x64
    - name: print detailed.log
      shell: pwsh
      run: |
          Get-Content build/detailed.log
    - name: build
      shell: pwsh
      run: |
        cmake --build build --config Debug --target install
    - name: test
      shell: pwsh
      run: |
        cmake --build build --config Debug --target `
          setup_tests_a-framework `
          setup_tests_examples `
          setup_tests_quick_tests
        ctest --test-dir build -C Debug --extra-verbose -E "step-100.debug|step-100.release"
    - name: show largest files
      # we are nearly at the limit (4 GB) for what a .lib can contain on Windows. Monitor the size by printing out the largest
      # files in the build directory
      run: |
        Get-ChildItem -Path build -Recurse -File -ErrorAction SilentlyContinue |
        Sort-Object Length -Descending |
        Select-Object -First 200 |
        Format-Table @{Name="Size(MB)"; Expression={[math]::Round($_.Length / 1MB, 2)}}, FullName -AutoSize
    - name: upload library
      # run only if a PR is merged into master
      if: ${{ github.ref == 'refs/heads/master' && matrix.os == 'windows-2025' }}
      uses: actions/upload-artifact@v7
      with:
        name: dealii-${{ matrix.os }}
        path: c:/project
    - name: upload CMakeConfigureLog
      uses: actions/upload-artifact@v7
      if: always()
      continue-on-error: true
      with:
        name: ${{ matrix.os }}-serial-CMakeConfigureLog.yaml
        path: build/CMakeFiles/CMakeConfigureLog.yaml
